/**
 * Apple App Store Connect Privacy Catalog
 * Complete list of categories, data types, and purposes
 * matching the App Privacy section in App Store Connect.
 */

export interface PrivacyDataType {
  id: string;
  label: string;
  description: string;
}

export interface PrivacyCategory {
  category: string;
  label: string;
  types: PrivacyDataType[];
}

export interface PrivacyPurpose {
  id: string;
  label: string;
  description: string;
}

export const PRIVACY_CATEGORIES: PrivacyCategory[] = [
  {
    category: "contact_info",
    label: "Contact Info",
    types: [
      {
        id: "Name",
        label: "Name",
        description: "Including first or last name",
      },
      {
        id: "Email Address",
        label: "Email Address",
        description: "Including but not limited to a hashed email address",
      },
      {
        id: "Phone Number",
        label: "Phone Number",
        description: "Including but not limited to a hashed phone number",
      },
      {
        id: "Physical Address",
        label: "Physical Address",
        description: "Such as home address, physical address, or mailing address",
      },
      {
        id: "Other User Contact Info",
        label: "Other User Contact Info",
        description: "Any other information that can be used to contact the user outside the app",
      },
    ],
  },
  {
    category: "health_fitness",
    label: "Health & Fitness",
    types: [
      {
        id: "Health",
        label: "Health",
        description: "Health and medical data, including from Clinical Health Records API, HealthKit API, MovementDisorderAPIs, or health-related human subject research",
      },
      {
        id: "Fitness",
        label: "Fitness",
        description: "Fitness and exercise data, including the Motion and Fitness API",
      },
    ],
  },
  {
    category: "financial",
    label: "Financial Info",
    types: [
      {
        id: "Payment Info",
        label: "Payment Info",
        description: "Such as form of payment, payment card number, or bank account number (Apple Pay is handled by the system and not included)",
      },
      {
        id: "Credit Info",
        label: "Credit Info",
        description: "Such as credit score",
      },
      {
        id: "Other Financial Info",
        label: "Other Financial Info",
        description: "Such as salary, income, assets, debts, or any other financial information",
      },
    ],
  },
  {
    category: "location",
    label: "Location",
    types: [
      {
        id: "Precise Location",
        label: "Precise Location",
        description: "Information that describes the location of a user or device with the same or greater resolution as a latitude and longitude with three or more decimal places",
      },
      {
        id: "Coarse Location",
        label: "Coarse Location",
        description: "Information that describes the location of a user or device with lower resolution than a latitude and longitude with three or more decimal places, such as Approximate Location Services",
      },
    ],
  },
  {
    category: "sensitive_info",
    label: "Sensitive Info",
    types: [
      {
        id: "Sensitive Info",
        label: "Sensitive Info",
        description: "Such as racial or ethnic data, sexual orientation, pregnancy or childbirth information, disability, religious or philosophical beliefs, trade union membership, political opinion, genetic information, or biometric data",
      },
    ],
  },
  {
    category: "contacts",
    label: "Contacts",
    types: [
      {
        id: "Contacts",
        label: "Contacts",
        description: "Such as a list of contacts in the user's phone, address book, or social graph",
      },
    ],
  },
  {
    category: "user_content",
    label: "User Content",
    types: [
      {
        id: "Emails or Text Messages",
        label: "Emails or Text Messages",
        description: "Including subject line, sender, recipients, and contents of the email or message",
      },
      {
        id: "Photos or Videos",
        label: "Photos or Videos",
        description: "The user's photos or videos",
      },
      {
        id: "Audio Data",
        label: "Audio Data",
        description: "The user's voice or sound recordings",
      },
      {
        id: "Gameplay Content",
        label: "Gameplay Content",
        description: "Such as user-generated content in-game",
      },
      {
        id: "Customer Support",
        label: "Customer Support",
        description: "Data generated by the user during a customer support request",
      },
      {
        id: "Other User Content",
        label: "Other User Content",
        description: "Any other user-generated content",
      },
    ],
  },
  {
    category: "browsing_history",
    label: "Browsing History",
    types: [
      {
        id: "Browsing History",
        label: "Browsing History",
        description: "Information about content the user has viewed that is not part of the app, such as websites",
      },
    ],
  },
  {
    category: "search_history",
    label: "Search History",
    types: [
      {
        id: "Search History",
        label: "Search History",
        description: "Information about searches performed in the app",
      },
    ],
  },
  {
    category: "identifiers",
    label: "Identifiers",
    types: [
      {
        id: "User ID",
        label: "User ID",
        description: "Such as screen name, handle, account ID, assigned user ID, customer number, or other user- or account-level ID that can be used to identify a particular user or account",
      },
      {
        id: "Device ID",
        label: "Device ID",
        description: "Such as the device's advertising identifier, or other device-level ID",
      },
    ],
  },
  {
    category: "purchases",
    label: "Purchases",
    types: [
      {
        id: "Purchase History",
        label: "Purchase History",
        description: "An account's or individual's purchases or purchase tendencies",
      },
    ],
  },
  {
    category: "usage_data",
    label: "Usage Data",
    types: [
      {
        id: "Product Interaction",
        label: "Product Interaction",
        description: "Such as app launches, taps, clicks, scrolling information, music listening data, video views, saved place in a game, video, or song, or other information about how the user interacts with the app",
      },
      {
        id: "Advertising Data",
        label: "Advertising Data",
        description: "Such as information about the advertisements the user has seen",
      },
      {
        id: "Other Usage Data",
        label: "Other Usage Data",
        description: "Any other data about user activity in the app",
      },
    ],
  },
  {
    category: "diagnostics",
    label: "Diagnostics",
    types: [
      {
        id: "Crash Data",
        label: "Crash Data",
        description: "Such as crash logs",
      },
      {
        id: "Performance Data",
        label: "Performance Data",
        description: "Such as launch time, hang rate, or energy use",
      },
      {
        id: "Other Diagnostic Data",
        label: "Other Diagnostic Data",
        description: "Any other data collected for the purposes of measuring technical diagnostics related to the app",
      },
    ],
  },
];

export const PRIVACY_PURPOSES: PrivacyPurpose[] = [
  {
    id: "third_party_advertising",
    label: "Third-Party Advertising",
    description: "Such as displaying third-party ads in your app, or sharing data with entities who display third-party ads",
  },
  {
    id: "developers_advertising",
    label: "Developer's Advertising or Marketing",
    description: "Such as displaying first-party ads in your app, sending marketing communications directly to your users, or sharing data with entities who will display your ads",
  },
  {
    id: "analytics",
    label: "Analytics",
    description: "Using data to evaluate user behavior, including to understand the effectiveness of existing product features, plan new features, or measure audience size or characteristics",
  },
  {
    id: "product_personalization",
    label: "Product Personalization",
    description: "Customizing what the user sees, such as a list of recommended products, posts, or suggestions",
  },
  {
    id: "app_functionality",
    label: "App Functionality",
    description: "Such as to authenticate the user, enable features, prevent fraud, implement security measures, ensure server up-time, minimize app crashes, improve scalability and performance, or perform customer support",
  },
  {
    id: "other_purposes",
    label: "Other Purposes",
    description: "Any other purposes not listed",
  },
];
