#!/usr/bin/env bash
# Sync the browser-safe ASO scoring engine from the backend repo.
# The engine is pure math with zero runtime imports (guarded by a backend
# test), so the copies run 1:1 in the browser for the free /aso-check tool.
# Re-run after any backend change to keyword-scoring.ts / scoring-types.ts.
set -euo pipefail

BACKEND="${1:-../appboard_backend}"
SRC="$BACKEND/src/modules/research"
DEST="$(dirname "$0")/../src/lib/aso-engine"

for f in scoring-types.ts keyword-scoring.ts; do
  if [ ! -f "$SRC/$f" ]; then
    echo "error: $SRC/$f not found (pass the backend path as arg 1)" >&2
    exit 1
  fi
  {
    echo "// GENERATED by scripts/sync-aso-engine.sh from appboard_backend"
    echo "// src/modules/research/$f - DO NOT EDIT HERE. Edit the backend"
    echo "// copy and re-run the sync."
    cat "$SRC/$f"
  } > "$DEST/$f"
  echo "synced $f"
done
